const Type = {
  SET_SIDEBARSTATE: 'SET_SIDEBARSTATE',
  BEGIN_DATA_REQUEST: 'BEGIN_DATA_REQUEST',
  SUCCESS_DATA_REQUEST: 'SUCCESS_DATA_REQUEST',
  FAIL_DATA_REQUEST: ' FAIL_DATA_REQUEST',
};

export default Type;
